-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin_db
(
    admin_id integer NOT NULL,
    admin_first_name character varying(16) NOT NULL,
    admin_middle_name character varying(16),
    admin_last_name character varying(16) NOT NULL,
    last_update_date date NOT NULL,
    last_update_by integer NOT NULL,
    PRIMARY KEY (admin_id)
);

CREATE TABLE IF NOT EXISTS public.user_db
(
    user_id integer NOT NULL,
    user_first_name character varying(16) NOT NULL,
    user_middle_name character varying(16),
    user_last_name character varying(16) NOT NULL,
    last_update_date date NOT NULL,
    last_update_by integer NOT NULL,
    user_name "char",
    user_password "char"
);

CREATE TABLE IF NOT EXISTS public.organization_db
(
    organization_id integer NOT NULL,
    org_room_code "char",
    verified_user_id integer,
    PRIMARY KEY (organization_id)
);

CREATE TABLE IF NOT EXISTS public.gaming_db
(
    game_id integer NOT NULL,
    user_name "char",
    user_password "char",
    user_id integer,
    PRIMARY KEY (game_id)
);

CREATE TABLE IF NOT EXISTS public.office_db
(
    office_id integer NOT NULL,
    user_name "char",
    user_password "char",
    user_id integer,
    org_room_code "char",
    organization_id integer,
    user_room_code "char",
    PRIMARY KEY (office_id)
);

CREATE TABLE IF NOT EXISTS public.education_db
(
    school_id integer NOT NULL,
    user_name "char",
    user_password "char",
    user_id integer,
    school_room_code "char",
    organization_id integer,
    user_room_code "char",
    PRIMARY KEY (organization_id)
);

CREATE TABLE IF NOT EXISTS public.school_db
(
    school_id integer NOT NULL,
    school_code "char",
    verified_user_id integer,
    PRIMARY KEY (school_id)
);

ALTER TABLE public.user_db
    ADD FOREIGN KEY (last_update_by)
    REFERENCES public.admin_db (last_update_by)
    NOT VALID;


ALTER TABLE public.user_db
    ADD FOREIGN KEY (last_update_date)
    REFERENCES public.admin_db (last_update_date)
    NOT VALID;


ALTER TABLE public.user_db
    ADD FOREIGN KEY (user_id)
    REFERENCES public.organization_db (verified_user_id)
    NOT VALID;


ALTER TABLE public.user_db
    ADD FOREIGN KEY (user_id)
    REFERENCES public.school_db (verified_user_id)
    NOT VALID;


ALTER TABLE public.user_db
    ADD FOREIGN KEY (user_id)
    REFERENCES public.gaming_db (user_id)
    NOT VALID;


ALTER TABLE public.user_db
    ADD FOREIGN KEY (user_id)
    REFERENCES public.office_db (user_id)
    NOT VALID;


ALTER TABLE public.user_db
    ADD FOREIGN KEY (user_id)
    REFERENCES public.education_db (user_id)
    NOT VALID;


ALTER TABLE public.school_db
    ADD FOREIGN KEY (verified_user_id)
    REFERENCES public.education_db (user_id)
    NOT VALID;


ALTER TABLE public.school_db
    ADD FOREIGN KEY (school_code)
    REFERENCES public.education_db (school_room_code)
    NOT VALID;


ALTER TABLE public.organization_db
    ADD FOREIGN KEY (verified_user_id)
    REFERENCES public.office_db (user_id)
    NOT VALID;


ALTER TABLE public.organization_db
    ADD FOREIGN KEY (org_room_code)
    REFERENCES public.office_db (org_room_code)
    NOT VALID;

END;
